export const FETCH_DATA_PENDING = 'FETCH_DATA_PENDING';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';

export const CHANGES_IN_RECORDS_PENDING ='CHANGES_IN_RECORDS_PENDING';
export const CHANGES_IN_RECORDS_SUCCESS ='CHANGES_IN_RECORDS_SUCCESS';
export const CHANGES_IN_RECORDS_ERROR ='CHANGES_IN_RECORDS_ERROR';
